### ISSUE TITLE
Bootstrap for 'latest' version broken

### ISSUE THREAD

**Issue by xfxian** [openbaton/bootstrap#17]
Hi everyone,

your deployment host currently has a broken functions file in the 'latest' profile:

`http://get.openbaton.org/bootstraps/latest/bootstrap-common-functions`

as you can see, there are no default versions set, i. e. 

`OPENBATON_NFVO_VERSION_DEFAULT=""`

Installation will fail later because of this parameter not being set and supplied to other functions.

Best regards,
Jacob

**Comment by xfxian** [comment]
By the way, when looking for a workaround, in the main boostrap file the variable `openbaton_bootstrap_version` is never set. The argument `--openbaton-bootstrap-version=X.Y.Z` explained in the usage is without function.

Currently you have to `export openbaton_bootstrap_version=4.0.0` or similar first in order to get the script running.

**Comment by flaviomu** [comment]
I am already testing a fix.

**Comment by flaviomu** [comment]
@xfxian yes the `openbaton_bootstrap_version` is set in line 25 of the main bootstrap file. 
You can export it manually before running the bootstrap or you can simply pass the bootstrap the argument `--openbaton-bootstrap-version=X.Y.Z` inline.

**Comment by xfxian** [comment]
I tried it, but it seemed not to be interpreted correctly. I had to set it manually.

**Comment by flaviomu** [comment]
It's strange, I have been using it all the time: I used it even this morning.

**Comment by flaviomu** [comment]
Commit https://github.com/openbaton/bootstrap/commit/5d5d4132a391b69ca15ff6feb839366c42ae7435 fixes the issue. 
@xfxian thanks for reporting it.

**Comment by xfxian** [comment]
Okay well, maybe I had a typo in the line or something. Anyway, thanks for the fix!
