### ISSUE TITLE
Unset variable Line 130 DEBIAN_FRONTEND

### ISSUE THREAD

**Issue by wittling** [openbaton/bootstrap#19]
Need to use a -z on variables before using them in evaluation expressions.

**Comment by gc4rella** [comment]
@wittling could you please provide the exact file (and its branch) you are referring to? In general, the variables are all set by default, and when no values are passed via config files, the default values are used.

**Comment by mpauls** [comment]
Seems to be outdated this issue. New bootstrap uses docker-compose only. Can be reopened if needed.
