### ISSUE TITLE
Bootstrap fail to export variable 'service_key'

### ISSUE THREAD

**Issue by mzanella** [openbaton/bootstrap#24]
Hi,

I followed the instruction in https://openbaton.github.io/documentation/nfvo-installation-deb/ but at the end of the script I encountered the following error
```bash
/dev/fd/63: 529: export: +-----+-----+-----+-----+-----+-----+-----+-----+: bad variable name
```
In particular I collected all the output in a file
[log.txt](https://github.com/openbaton/bootstrap/files/2149690/log.txt)
and the problem seems to be a variable that is not correctly assigned. 

I'm trying to install Openbaton on Ubuntu server 16.04 with the following configuration file 
[conf.txt](https://github.com/openbaton/bootstrap/files/2149703/conf.txt)

Cheers,
Marco

**Comment by mpauls** [comment]
We moved to docker-compose for bootstrapping. service-key can either be set later or is requested directly by the 'service' itself. Problem shall be solved so the issue can be closed.
