### ISSUE TITLE
Fix urandom in java.security

### ISSUE THREAD

**Issue by lorenzotomasini** [openbaton/bootstrap#7]
Fix java known bug by changing the line:

``` properties
securerandom.source=file:/dev/urandom
```

to

``` properties
securerandom.source=file:/dev/./urandom
```

in the file: /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/security/java.security

**Comment by KLuka** [comment]
This can also be done by using runtime define flag with `-D` option. Like this for example:

```
/usr/bin/java -Djava.security.egd=file:/dev/./urandom -jar /opt/openbaton/nfvo/openbaton.jar
```

**Comment by lorenzotomasini** [comment]
Hi @KLuka 

This doesn't work all the time for me. The only way i was always able to make it work is by changing the file. I understand it should be the same but still I sometime faced the long startup waiting time using the command line flag.

**Comment by KLuka** [comment]
Hm, I think we had the same problems when we used `-Djava.security.egd=file:/dev/./urandom` at the end of command line. Now we are using it right after `java` and it is working as expected.
